"use client";
import { ChangeEvent, FormEvent, useRef, useState } from "react";
import { Area, DataSource, MeteoCase, ProductId, SelectionMode } from "@/types";
import { Panel } from "@/components/common/Panel";
import { exportJson, exportPdf, exportPngCard, exportTxt, shareCase } from "@/lib/exportCase";
import { importMeteoCases } from "@/lib/caseSchema";
type Props = { area: Area; products: ProductId[]; frameA: number; frameB: number; startTime: string; endTime: string; source: DataSource; selectionMode: SelectionMode; onSave: (item: MeteoCase) => void; onImport: (items: MeteoCase[]) => void };
export function CaseEditor({ area, products, frameA, frameB, startTime, endTime, source, selectionMode, onSave, onImport }: Props) {
  const [title, setTitle] = useState(""); const [note, setNote] = useState(""); const [tags, setTags] = useState(""); const [last, setLast] = useState<MeteoCase | null>(null); const [message, setMessage] = useState(""); const input = useRef<HTMLInputElement>(null);
  function create(event: FormEvent) { event.preventDefault(); const item: MeteoCase = { id: crypto.randomUUID(), title: title.trim() || `Исследование: ${area.name}`, area, products, productId: products[0], frameA, frameB, startTime, endTime, note, tags: tags.split(",").map((tag) => tag.trim()).filter(Boolean), createdAt: new Date().toISOString(), mode: source === "eumetsat" ? "LIVE" : "UNAVAILABLE", source, selectionMode, schemaVersion: 2 }; onSave(item); setLast(item); setTitle(""); setNote(""); setTags(""); setMessage("Кейс сохранён в локальном хранилище браузера."); }
  async function loadFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; try { onImport(importMeteoCases(await file.text())); setMessage("Кейс импортирован."); } catch (error) { setMessage(error instanceof Error ? error.message : "Не удалось импортировать файл."); } event.target.value = ""; }
  return <Panel title="СОХРАНИТЬ МЕТЕОРОЛОГИЧЕСКИЙ КЕЙС" className="caseEditor"><form onSubmit={create}><label>НАЗВАНИЕ<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder={`Исследование: ${area.name}`} /></label><label>ТЕГИ<input value={tags} onChange={(event) => setTags(event.target.value)} placeholder="облака, фронт, проверка" /></label><label>ЗАМЕТКА<textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Контекст наблюдения (не является прогнозом)" rows={3} /></label><button type="submit">СОХРАНИТЬ КЕЙС</button></form><input ref={input} className="srOnly" type="file" accept="application/json,.json" onChange={loadFile} /><div className="exportRow"><button onClick={() => input.current?.click()}>ИМПОРТ JSON</button>{last && <><button onClick={() => exportTxt(last)}>TXT</button><button onClick={() => exportJson(last)}>JSON</button><button onClick={() => exportPngCard(last)}>PNG</button><button onClick={() => exportPdf(last)}>PDF</button><button onClick={() => shareCase(last).then(() => setMessage("Ссылка скопирована в буфер обмена."))}>ССЫЛКА</button></>}</div>{message && <p className="hint" role="status">{message}</p>}</Panel>;
}
