"use client";
import { useEffect, useState } from "react";
import { ComparisonMode, Frame } from "@/types";
import { Panel } from "@/components/common/Panel";

export function ComparisonPanel({ frames, frameA, frameB, onFrameA, onFrameB }: { frames: Frame[]; frameA: number; frameB: number; onFrameA: (v: number) => void; onFrameB: (v: number) => void }) {
  const [split, setSplit] = useState(52); const [mode, setMode] = useState<ComparisonMode>("split"); const [showA, setShowA] = useState(true); const [opacity, setOpacity] = useState(50);
  useEffect(() => { if (mode !== "blink") return; const timer = window.setInterval(() => setShowA((value) => !value), 650); return () => window.clearInterval(timer); }, [mode]);
  const label = mode === "difference" ? "ВИЗУАЛЬНАЯ РАЗНОСТЬ" : showA ? "A" : "B";
  return <Panel title="СРАВНЕНИЕ КАДРОВ · A / B" className="comparison"><div className="compareToolbar"><label>КАДР A <select value={frameA} onChange={(event) => onFrameA(Number(event.target.value))}>{frames.map((frame) => <option key={frame.id} value={frame.index}>{frame.label}</option>)}</select></label><label>КАДР B <select value={frameB} onChange={(event) => onFrameB(Number(event.target.value))}>{frames.map((frame) => <option key={frame.id} value={frame.index}>{frame.label}</option>)}</select></label></div><div className="modeButtons" role="group" aria-label="Режим сравнения">{(["split", "horizontal", "opacity", "blink", "difference"] as ComparisonMode[]).map((item) => <button key={item} className={mode === item ? "active" : ""} onClick={() => setMode(item)}>{({ split: "ВЕРТ.", horizontal: "ГОРИЗ.", opacity: "ПРОЗР.", blink: "МИГАНИЕ", difference: "РАЗНОСТЬ" })[item]}</button>)}</div><div className={`compareCanvas ${mode}`}><div className="compareField fieldA" style={mode === "blink" && !showA ? { opacity: 0 } : mode === "opacity" ? { opacity: opacity / 100 } : undefined}><b>{label}</b><span>{frames[frameA]?.label}</span></div>{mode !== "blink" && <div className="compareField fieldB" style={mode === "split" ? { clipPath: `inset(0 0 0 ${split}%)` } : mode === "horizontal" ? { clipPath: `inset(${split}% 0 0 0)` } : mode === "opacity" ? { opacity: 1 - opacity / 100 } : undefined}><b>{mode === "difference" ? "Δ RGB" : "B"}</b><span>{frames[frameB]?.label}</span></div>}{(mode === "split" || mode === "horizontal") && <input className="comparisonSlider" type="range" min="0" max="100" value={split} onChange={(event) => setSplit(Number(event.target.value))} aria-label="Граница сравнения кадров" />}{mode === "opacity" && <label className="opacityControl">A: {opacity}%<input type="range" min="0" max="100" value={opacity} onChange={(event) => setOpacity(Number(event.target.value))} /></label>}</div><p className="hint">Режим «Разность» показывает только визуальное различие пикселей. Метеорологические выводы требуют проверки исходных данных и контекста.</p></Panel>;
}
