"use client";
import { useMemo, useState } from "react";
import { PRODUCTS, productById } from "@/config/products";
import { Area, ProductId, TraceNode } from "@/types";
import { Panel } from "@/components/common/Panel";

export function AtmosphericTraceGraph({ area, selected, frameLabel }: { area: Area; selected: ProductId; frameLabel: string }) {
  const nodes = useMemo<TraceNode[]>(() => [{ id: "area", title: area.name, type: "область", description: `Выбранная область: ${area.lat.toFixed(4)}, ${area.lon.toFixed(4)}.` }, { id: "source", title: "EUMETSAT", type: "источник", description: "Официальный источник спутниковых продуктов. Доступность WMS проверяется отдельно для каждого запроса." }, ...PRODUCTS.map((product) => ({ id: product.id, title: product.name, type: "продукт", description: product.description, productId: product.id }))], [area]);
  const [active, setActive] = useState("area"); const current = nodes.find((node) => node.id === active) ?? nodes[0];
  const locations: Record<string, [number, number]> = { area: [50, 51], source: [25, 23], geocolour: [75, 20], ir105: [82, 38], cloudHeight: [76, 56], cloudTemperature: [72, 75], cloudType: [28, 75], lightning: [18, 51] };
  return <Panel title="КАРТА АТМОСФЕРНОГО СЛЕДА" className="tracePanel"><div className="traceWrap"><svg className="traceSvg" viewBox="0 0 100 100" role="img" aria-label="Граф выбранной области, источника и спутниковых продуктов"><defs><pattern id="grid" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M 5 0 L 0 0 0 5" fill="none" stroke="currentColor" strokeOpacity=".12" strokeWidth=".25" /></pattern></defs><rect width="100" height="100" fill="url(#grid)" />{nodes.slice(1).map((node) => <line key={node.id} x1={locations.area[0]} y1={locations.area[1]} x2={locations[node.id][0]} y2={locations[node.id][1]} className="traceLine" />)}{nodes.map((node) => { const [x, y] = locations[node.id]; return <g key={node.id} className={active === node.id ? "traceNode isActive" : "traceNode"} onClick={() => setActive(node.id)} role="button" tabIndex={0} aria-label={`Выбрать узел ${node.title}`} onKeyDown={(event) => event.key === "Enter" && setActive(node.id)}><circle cx={x} cy={y} r={node.id === "area" ? "4.6" : "3.1"} /><text x={x} y={y + (node.id === "area" ? 8 : 6)}>{node.title}</text></g>; })}</svg><aside className="nodeDetails"><p className="panelLabel">ВЫБРАННЫЙ УЗЕЛ</p><h3>{current.title}</h3><dl><dt>ТИП</dt><dd>{current.type}</dd><dt>ИСТОЧНИК</dt><dd>{current.productId ? "EUMETSAT" : current.id === "area" ? "пользователь" : "EUMETSAT"}</dd><dt>ВРЕМЯ</dt><dd>{frameLabel}</dd><dt>СТАТУС</dt><dd>проверяется по запросу</dd>{current.productId && <><dt>ЕДИНИЦЫ</dt><dd>{productById(current.productId).units}</dd></>}</dl><p>{current.description}</p></aside></div><p className="traceCaption">Связи показывают конфигурацию исследования, а не автоматический метеорологический вывод.</p></Panel>;
}
